components/vm/20-secrets.tf, components/vm/25-vms.tf, environments/prod/prod.tfvars, environments/stg/stg.tfvars
N/A
Prefix usernames with `crimeportal_`
**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```
=> fix: prefix usernames

components/core/20-core-infra.tf, environments/stg/stg.tfvars
=> chore: update module ref to test changes

components/database/11-inputs-optional.tf, components/database/12-interpolated-defaults.tf, components/database/20-postgresql.tf
N/A
Added crime portal DB admins group to Entra Admins on Postgresql Flexible.
=> feat: add db admin group & bump postgresql version to 15

components/database/20-postgresql.tf
N/A
Set `azure.extensions` PostgreSQL server parameter.
=> feat: added azure.extensions pgsql server parameter

components/database/20-postgresql.tf
=> Enable pg_stat_statements.

environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15483
Updated NSG rules to change the LDAP port & allow intra subnet connectivity for both LDAP and Frontend VMs.
=> feat: update nsg rules

environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-15164
Added Internal LB config.
=> Added Internal LB config

environments/prod/prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16434
Updated core resources prior to the deployment of the AppGW
=> feat: renamed subnet and added appgw supporting resources

environments/prod/prod.tfvars
=> fix typo on backend

components/app-gateway/12-interpolated-defaults.tf
=> fix-keyvault-id-typo

components/app-gateway/12-interpolated-defaults.tf
fix typo on data source keyvault
=> fix typo on data source keyvault

components/app-gateway/10-inputs-required.tf, components/app-gateway/12-interpolated-defaults.tf, components/app-gateway/20-app-gateway.tf, environments/prod/prod.tfvars
=> fix secret issue

components/app-gateway/10-inputs-required.tf, components/app-gateway/12-interpolated-defaults.tf, components/app-gateway/20-app-gateway.tf, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-16438
Points the staging app gateway to use the certificates provisioned by ACME.
=> Automate SSL certificate provisioning in STG

environments/prod/prod.tfvars
N/A
Switch Crime portal over to use the Lets Encrypt certificate
=> feat: switch AppGW Listener over to Lets Encrypt Certificate

README.md, components/database/12-interpolated-defaults.tf, components/database/20-postgresql.tf
See [DTSPO-18218](https://tools.hmcts.net/jira/browse/DTSPO-18218)
=> feat: update docs and add psql creds to kv

components/vm/00-init.tf, components/vm/11-inputs-optional.tf, components/vm/25-vms.tf, environments/prod/prod.tfvars, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18847
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
Rolling back install-clamav-update-splunk branch as discussed with Brendon, we going to wait for Alex to get back from leave before putting it back to this repo.
Changes will rollout AMA agents on the Staging and production VMs.
=> DTSPO-18847 -  ama deploy on staging and production

components/vm/00-init.tf, components/vm/10-inputs-required.tf, components/vm/12-interpolated-defaults.tf, components/vm/25-vms.tf, components/vm/outputs.tf, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18758
Adding input to VM tfvars for XDR
Using try to check if a value exists and default to no
Adding extra tags input and creating merge with common tags
=> XDR installation update

components/vm/10-inputs-required.tf, components/vm/25-vms.tf, environments/stg/stg.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-18758
Removing extension for docker installs, replacing with updated bootstrap input to install docker via single run command script from Bootstrap module
=> Removing extension for docker installs, replacing with updated bootstrap input to install docker via single run command script from Bootstrap module

components/vm/25-vms.tf, environments/prod/prod.tfvars, environments/stg/stg.tfvars
See [DTSPO-18760](https://tools.hmcts.net/jira/browse/DTSPO-18760)
add XDR and docker to prod environment
=> Dtspo 18760 prod deploy xsiam xdr agent to crime portal virtual machine

components/vm/25-vms.tf
https://tools.hmcts.net/jira/browse/DTSPO-18828
Updated feature branch back to master
=> DTSPO-18828 - updated feature branch back to master

README.md
https://tools.hmcts.net/jira/browse/DTSPO-18218
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
OAT outstanding tasks
=> Updating OAT outstanding actions

components/database/11-inputs-optional.tf, components/database/20-postgresql.tf, environments/stg/stg.tfvars
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
=> fix: correct terraform errors using azurerm v4.x

azure-pipelines.yaml
https://tools.hmcts.net/jira/browse/DTSPO-25700
Ubuntu image version update to latest
=> Ubuntu image version update to latest
